#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 31
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 10

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_PIPE = 2,
  anon_sym_GT = 3,
  anon_sym_PLUS = 4,
  anon_sym_DASH = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_not = 8,
  anon_sym_QMARK = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  sym_int = 12,
  sym_float = 13,
  sym_str = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  anon_sym_COLON = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_fn = 21,
  anon_sym_EQ = 22,
  anon_sym_struct = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  sym_source_file = 26,
  sym_expr = 27,
  sym_binary_op = 28,
  sym_unary_op = 29,
  sym_paren = 30,
  sym_bool = 31,
  sym_param = 32,
  sym_params = 33,
  sym_block = 34,
  sym_fn = 35,
  sym_args = 36,
  sym_call = 37,
  sym_def = 38,
  sym_field = 39,
  sym_fields = 40,
  sym_struct = 41,
  sym_array = 42,
  sym_pair = 43,
  sym_pairs = 44,
  sym_map = 45,
  sym_tuple = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_params_repeat1 = 48,
  aux_sym_args_repeat1 = 49,
  aux_sym_fields_repeat1 = 50,
  aux_sym_pairs_repeat1 = 51,
  aux_sym_tuple_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_PIPE] = "|",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_not] = "not",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_str] = "str",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [sym_paren] = "paren",
  [sym_bool] = "bool",
  [sym_param] = "param",
  [sym_params] = "params",
  [sym_block] = "block",
  [sym_fn] = "fn",
  [sym_args] = "args",
  [sym_call] = "call",
  [sym_def] = "def",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct] = "struct",
  [sym_array] = "array",
  [sym_pair] = "pair",
  [sym_pairs] = "pairs",
  [sym_map] = "map",
  [sym_tuple] = "tuple",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_pairs_repeat1] = "pairs_repeat1",
  [aux_sym_tuple_repeat1] = "tuple_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_str] = sym_str,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [sym_paren] = sym_paren,
  [sym_bool] = sym_bool,
  [sym_param] = sym_param,
  [sym_params] = sym_params,
  [sym_block] = sym_block,
  [sym_fn] = sym_fn,
  [sym_args] = sym_args,
  [sym_call] = sym_call,
  [sym_def] = sym_def,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct] = sym_struct,
  [sym_array] = sym_array,
  [sym_pair] = sym_pair,
  [sym_pairs] = sym_pairs,
  [sym_map] = sym_map,
  [sym_tuple] = sym_tuple,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_pairs_repeat1] = aux_sym_pairs_repeat1,
  [aux_sym_tuple_repeat1] = aux_sym_tuple_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_pairs] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pairs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_fn = 3,
  field_key = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_params = 8,
  field_return_type = 9,
  field_right = 10,
  field_type = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_fn] = "fn",
  [field_key] = "key",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 1},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 2},
  [9] = {.index = 17, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [5] =
    {field_fn, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_args, 2},
    {field_fn, 0},
  [10] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
  [13] =
    {field_body, 4},
    {field_return_type, 3},
  [15] =
    {field_name, 0},
    {field_type, 2},
  [17] =
    {field_body, 5},
    {field_params, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 1,
        '(', 11,
        ')', 12,
        '*', 8,
        '+', 6,
        ',', 18,
        '-', 7,
        '/', 9,
        ':', 17,
        '=', 21,
        '>', 5,
        '?', 10,
        '[', 22,
        ']', 23,
        '{', 19,
        '|', 4,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 's') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(105),
    [sym_expr] = STATE(59),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [2] = {
    [sym_expr] = STATE(49),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(27),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(27),
  },
  [3] = {
    [sym_expr] = STATE(63),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_args_repeat1] = STATE(79),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(31),
  },
  [4] = {
    [sym_expr] = STATE(59),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_symbol] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(38),
    [anon_sym_STAR] = ACTIONS(38),
    [anon_sym_not] = ACTIONS(41),
    [anon_sym_QMARK] = ACTIONS(38),
    [anon_sym_LPAREN] = ACTIONS(44),
    [sym_int] = ACTIONS(47),
    [sym_float] = ACTIONS(50),
    [sym_str] = ACTIONS(50),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(56),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_fn] = ACTIONS(59),
    [anon_sym_struct] = ACTIONS(62),
    [anon_sym_LBRACK] = ACTIONS(65),
  },
  [5] = {
    [sym_expr] = STATE(58),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_tuple_repeat1] = STATE(10),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(68),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [6] = {
    [sym_expr] = STATE(59),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [7] = {
    [sym_expr] = STATE(59),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [8] = {
    [sym_expr] = STATE(58),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_tuple_repeat1] = STATE(8),
    [sym_symbol] = ACTIONS(74),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_not] = ACTIONS(80),
    [anon_sym_QMARK] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(86),
    [sym_int] = ACTIONS(88),
    [sym_float] = ACTIONS(91),
    [sym_str] = ACTIONS(91),
    [anon_sym_true] = ACTIONS(94),
    [anon_sym_false] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_fn] = ACTIONS(100),
    [anon_sym_struct] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(106),
  },
  [9] = {
    [sym_expr] = STATE(59),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [10] = {
    [sym_expr] = STATE(58),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [aux_sym_tuple_repeat1] = STATE(8),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(111),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [11] = {
    [sym_expr] = STATE(61),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_args] = STATE(101),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(113),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [12] = {
    [sym_expr] = STATE(69),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(115),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [13] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(117),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [14] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(119),
  },
  [15] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(121),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [16] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(123),
  },
  [17] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(125),
  },
  [18] = {
    [sym_expr] = STATE(65),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [19] = {
    [sym_expr] = STATE(42),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [20] = {
    [sym_expr] = STATE(54),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [21] = {
    [sym_expr] = STATE(66),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [22] = {
    [sym_expr] = STATE(57),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [23] = {
    [sym_expr] = STATE(64),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [24] = {
    [sym_expr] = STATE(68),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [25] = {
    [sym_expr] = STATE(70),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [26] = {
    [sym_expr] = STATE(49),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [27] = {
    [sym_expr] = STATE(62),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [28] = {
    [sym_expr] = STATE(67),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [29] = {
    [sym_expr] = STATE(55),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [30] = {
    [sym_expr] = STATE(56),
    [sym_binary_op] = STATE(48),
    [sym_unary_op] = STATE(48),
    [sym_paren] = STATE(48),
    [sym_bool] = STATE(48),
    [sym_fn] = STATE(48),
    [sym_call] = STATE(48),
    [sym_def] = STATE(48),
    [sym_struct] = STATE(48),
    [sym_array] = STATE(2),
    [sym_map] = STATE(48),
    [sym_tuple] = STATE(48),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(129), 1,
      anon_sym_COLON,
    ACTIONS(131), 1,
      anon_sym_EQ,
    ACTIONS(127), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(27), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [35] = 2,
    ACTIONS(135), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(133), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [65] = 2,
    ACTIONS(139), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(137), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [95] = 2,
    ACTIONS(143), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(141), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [125] = 2,
    ACTIONS(147), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(145), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [155] = 2,
    ACTIONS(151), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(149), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [185] = 2,
    ACTIONS(155), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(153), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [215] = 2,
    ACTIONS(159), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(157), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [245] = 2,
    ACTIONS(163), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(161), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [275] = 2,
    ACTIONS(167), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(165), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [305] = 2,
    ACTIONS(171), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(169), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [335] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(175), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(173), 11,
      ts_builtin_sym_end,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [373] = 2,
    ACTIONS(187), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(185), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [403] = 2,
    ACTIONS(191), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(189), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [433] = 2,
    ACTIONS(195), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(193), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [463] = 2,
    ACTIONS(199), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(197), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [493] = 2,
    ACTIONS(203), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(201), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [523] = 2,
    ACTIONS(127), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(27), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [553] = 3,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(207), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(205), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [585] = 2,
    ACTIONS(211), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(209), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [615] = 2,
    ACTIONS(215), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(213), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [645] = 2,
    ACTIONS(219), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(217), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [675] = 2,
    ACTIONS(223), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(221), 18,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [705] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(227), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(225), 11,
      ts_builtin_sym_end,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [743] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(231), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(229), 13,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [779] = 4,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(231), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(229), 15,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [813] = 3,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(231), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(229), 17,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [845] = 7,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(235), 6,
      anon_sym_QMARK,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
    ACTIONS(233), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
  [881] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(239), 7,
      ts_builtin_sym_end,
      anon_sym_QMARK,
      sym_float,
      sym_str,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(241), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
  [915] = 2,
    ACTIONS(243), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(86), 9,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
  [936] = 7,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_args_repeat1,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [961] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(249), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [982] = 7,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_args_repeat1,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1007] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(253), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1027] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(255), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1049] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(257), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1069] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(259), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1089] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(255), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_block,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1111] = 6,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1133] = 5,
    ACTIONS(183), 1,
      anon_sym_LPAREN,
    ACTIONS(265), 1,
      anon_sym_EQ,
    ACTIONS(177), 2,
      anon_sym_PIPE,
      anon_sym_GT,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1152] = 3,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_args_repeat1,
    ACTIONS(249), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1163] = 4,
    ACTIONS(270), 1,
      sym_symbol,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_param,
    STATE(103), 1,
      sym_params,
  [1176] = 4,
    ACTIONS(274), 1,
      sym_symbol,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      sym_pair,
    STATE(106), 1,
      sym_pairs,
  [1189] = 4,
    ACTIONS(278), 1,
      sym_symbol,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_field,
    STATE(97), 1,
      sym_fields,
  [1202] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_fields_repeat1,
  [1212] = 3,
    ACTIONS(119), 1,
      anon_sym_RBRACK,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_args_repeat1,
  [1222] = 3,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_fields_repeat1,
  [1232] = 3,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_params_repeat1,
  [1242] = 3,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_args_repeat1,
  [1252] = 3,
    ACTIONS(274), 1,
      sym_symbol,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_pair,
  [1262] = 3,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      aux_sym_pairs_repeat1,
  [1272] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      aux_sym_params_repeat1,
  [1282] = 3,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_args_repeat1,
  [1292] = 3,
    ACTIONS(304), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      aux_sym_pairs_repeat1,
  [1302] = 3,
    ACTIONS(274), 1,
      sym_symbol,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_pair,
  [1312] = 3,
    ACTIONS(311), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_fields_repeat1,
  [1322] = 3,
    ACTIONS(278), 1,
      sym_symbol,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_field,
  [1332] = 3,
    ACTIONS(278), 1,
      sym_symbol,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_field,
  [1342] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_pairs_repeat1,
  [1352] = 3,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    ACTIONS(324), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_params_repeat1,
  [1362] = 1,
    ACTIONS(314), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1367] = 1,
    ACTIONS(322), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1372] = 2,
    ACTIONS(274), 1,
      sym_symbol,
    STATE(94), 1,
      sym_pair,
  [1379] = 1,
    ACTIONS(307), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1384] = 2,
    ACTIONS(278), 1,
      sym_symbol,
    STATE(91), 1,
      sym_field,
  [1391] = 2,
    ACTIONS(270), 1,
      sym_symbol,
    STATE(92), 1,
      sym_param,
  [1398] = 1,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
  [1402] = 1,
    ACTIONS(329), 1,
      anon_sym_COLON,
  [1406] = 1,
    ACTIONS(331), 1,
      anon_sym_LPAREN,
  [1410] = 1,
    ACTIONS(333), 1,
      anon_sym_COLON,
  [1414] = 1,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [1418] = 1,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
  [1422] = 1,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [1426] = 1,
    ACTIONS(341), 1,
      anon_sym_COLON,
  [1430] = 1,
    ACTIONS(343), 1,
      ts_builtin_sym_end,
  [1434] = 1,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(31)] = 0,
  [SMALL_STATE(32)] = 35,
  [SMALL_STATE(33)] = 65,
  [SMALL_STATE(34)] = 95,
  [SMALL_STATE(35)] = 125,
  [SMALL_STATE(36)] = 155,
  [SMALL_STATE(37)] = 185,
  [SMALL_STATE(38)] = 215,
  [SMALL_STATE(39)] = 245,
  [SMALL_STATE(40)] = 275,
  [SMALL_STATE(41)] = 305,
  [SMALL_STATE(42)] = 335,
  [SMALL_STATE(43)] = 373,
  [SMALL_STATE(44)] = 403,
  [SMALL_STATE(45)] = 433,
  [SMALL_STATE(46)] = 463,
  [SMALL_STATE(47)] = 493,
  [SMALL_STATE(48)] = 523,
  [SMALL_STATE(49)] = 553,
  [SMALL_STATE(50)] = 585,
  [SMALL_STATE(51)] = 615,
  [SMALL_STATE(52)] = 645,
  [SMALL_STATE(53)] = 675,
  [SMALL_STATE(54)] = 705,
  [SMALL_STATE(55)] = 743,
  [SMALL_STATE(56)] = 779,
  [SMALL_STATE(57)] = 813,
  [SMALL_STATE(58)] = 845,
  [SMALL_STATE(59)] = 881,
  [SMALL_STATE(60)] = 915,
  [SMALL_STATE(61)] = 936,
  [SMALL_STATE(62)] = 961,
  [SMALL_STATE(63)] = 982,
  [SMALL_STATE(64)] = 1007,
  [SMALL_STATE(65)] = 1027,
  [SMALL_STATE(66)] = 1049,
  [SMALL_STATE(67)] = 1069,
  [SMALL_STATE(68)] = 1089,
  [SMALL_STATE(69)] = 1111,
  [SMALL_STATE(70)] = 1133,
  [SMALL_STATE(71)] = 1152,
  [SMALL_STATE(72)] = 1163,
  [SMALL_STATE(73)] = 1176,
  [SMALL_STATE(74)] = 1189,
  [SMALL_STATE(75)] = 1202,
  [SMALL_STATE(76)] = 1212,
  [SMALL_STATE(77)] = 1222,
  [SMALL_STATE(78)] = 1232,
  [SMALL_STATE(79)] = 1242,
  [SMALL_STATE(80)] = 1252,
  [SMALL_STATE(81)] = 1262,
  [SMALL_STATE(82)] = 1272,
  [SMALL_STATE(83)] = 1282,
  [SMALL_STATE(84)] = 1292,
  [SMALL_STATE(85)] = 1302,
  [SMALL_STATE(86)] = 1312,
  [SMALL_STATE(87)] = 1322,
  [SMALL_STATE(88)] = 1332,
  [SMALL_STATE(89)] = 1342,
  [SMALL_STATE(90)] = 1352,
  [SMALL_STATE(91)] = 1362,
  [SMALL_STATE(92)] = 1367,
  [SMALL_STATE(93)] = 1372,
  [SMALL_STATE(94)] = 1379,
  [SMALL_STATE(95)] = 1384,
  [SMALL_STATE(96)] = 1391,
  [SMALL_STATE(97)] = 1398,
  [SMALL_STATE(98)] = 1402,
  [SMALL_STATE(99)] = 1406,
  [SMALL_STATE(100)] = 1410,
  [SMALL_STATE(101)] = 1414,
  [SMALL_STATE(102)] = 1418,
  [SMALL_STATE(103)] = 1422,
  [SMALL_STATE(104)] = 1426,
  [SMALL_STATE(105)] = 1430,
  [SMALL_STATE(106)] = 1434,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6, 0, 9),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6, 0, 9),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 5),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 3),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, 0, 7),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, 0, 7),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 6),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 6),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, 0, 2),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, 0, 2),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tuple_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 8),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 4),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pairs_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pairs_repeat1, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 3, 0, 0),
  [311] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 1, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [324] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [343] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_smith(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
