#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_GT = 2,
  anon_sym_PLUS = 3,
  anon_sym_DASH = 4,
  anon_sym_STAR = 5,
  anon_sym_SLASH = 6,
  anon_sym_not = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  sym_int = 10,
  sym_float = 11,
  sym_str = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_COLON = 15,
  anon_sym_COMMA = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_fn = 19,
  anon_sym_EQ = 20,
  anon_sym_struct = 21,
  sym_source_file = 22,
  sym_expr = 23,
  sym_binary_op = 24,
  sym_unary_op = 25,
  sym_paren = 26,
  sym_bool = 27,
  sym_param = 28,
  sym_params = 29,
  sym_block = 30,
  sym_fn = 31,
  sym_args = 32,
  sym_call = 33,
  sym_def = 34,
  sym_field = 35,
  sym_fields = 36,
  sym_struct = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_params_repeat1 = 39,
  aux_sym_args_repeat1 = 40,
  aux_sym_fields_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_str] = "str",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [sym_paren] = "paren",
  [sym_bool] = "bool",
  [sym_param] = "param",
  [sym_params] = "params",
  [sym_block] = "block",
  [sym_fn] = "fn",
  [sym_args] = "args",
  [sym_call] = "call",
  [sym_def] = "def",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct] = "struct",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_str] = sym_str,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [sym_paren] = sym_paren,
  [sym_bool] = sym_bool,
  [sym_param] = sym_param,
  [sym_params] = sym_params,
  [sym_block] = sym_block,
  [sym_fn] = sym_fn,
  [sym_args] = sym_args,
  [sym_call] = sym_call,
  [sym_def] = sym_def,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct] = sym_struct,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_fn = 3,
  field_left = 4,
  field_name = 5,
  field_operator = 6,
  field_params = 7,
  field_return_type = 8,
  field_right = 9,
  field_type = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_fn] = "fn",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 1},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [5] =
    {field_fn, 0},
  [6] =
    {field_args, 2},
    {field_fn, 0},
  [8] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
  [11] =
    {field_body, 4},
    {field_return_type, 3},
  [13] =
    {field_name, 0},
    {field_type, 2},
  [15] =
    {field_body, 5},
    {field_params, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 1,
        '(', 9,
        ')', 10,
        '*', 7,
        '+', 5,
        ',', 16,
        '-', 6,
        '/', 8,
        ':', 15,
        '=', 19,
        '>', 4,
        '{', 17,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 's') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(67),
    [sym_expr] = STATE(38),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_struct] = ACTIONS(21),
  },
  [2] = {
    [sym_expr] = STATE(38),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_symbol] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(28),
    [anon_sym_not] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(34),
    [sym_int] = ACTIONS(37),
    [sym_float] = ACTIONS(40),
    [sym_str] = ACTIONS(40),
    [anon_sym_true] = ACTIONS(43),
    [anon_sym_false] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_fn] = ACTIONS(46),
    [anon_sym_struct] = ACTIONS(49),
  },
  [3] = {
    [sym_expr] = STATE(38),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_struct] = ACTIONS(21),
  },
  [4] = {
    [sym_expr] = STATE(39),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_args] = STATE(65),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(54),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_struct] = ACTIONS(21),
  },
  [5] = {
    [sym_expr] = STATE(38),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_struct] = ACTIONS(21),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(58),
    [sym_symbol] = ACTIONS(60),
    [anon_sym_GT] = ACTIONS(58),
    [anon_sym_PLUS] = ACTIONS(58),
    [anon_sym_DASH] = ACTIONS(58),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_SLASH] = ACTIONS(58),
    [anon_sym_not] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(58),
    [anon_sym_RPAREN] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [sym_float] = ACTIONS(58),
    [sym_str] = ACTIONS(58),
    [anon_sym_true] = ACTIONS(60),
    [anon_sym_false] = ACTIONS(60),
    [anon_sym_COLON] = ACTIONS(62),
    [anon_sym_COMMA] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(58),
    [anon_sym_RBRACE] = ACTIONS(58),
    [anon_sym_fn] = ACTIONS(60),
    [anon_sym_EQ] = ACTIONS(64),
    [anon_sym_struct] = ACTIONS(60),
  },
  [7] = {
    [sym_expr] = STATE(38),
    [sym_binary_op] = STATE(21),
    [sym_unary_op] = STATE(21),
    [sym_paren] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_fn] = STATE(21),
    [sym_call] = STATE(21),
    [sym_def] = STATE(21),
    [sym_struct] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(66),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_struct] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(68), 13,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [28] = 2,
    ACTIONS(76), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(74), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [54] = 2,
    ACTIONS(80), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(78), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [80] = 2,
    ACTIONS(84), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(82), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [106] = 6,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(88), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [140] = 6,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(96), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [174] = 2,
    ACTIONS(102), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(100), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [200] = 2,
    ACTIONS(106), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(104), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [226] = 2,
    ACTIONS(110), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(108), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [252] = 2,
    ACTIONS(114), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(112), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [278] = 3,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(116), 13,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [306] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(118), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [338] = 4,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(118), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(116), 11,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [368] = 2,
    ACTIONS(60), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(58), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [394] = 2,
    ACTIONS(122), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(120), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [420] = 2,
    ACTIONS(126), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(124), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [446] = 2,
    ACTIONS(130), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(128), 14,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [472] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(41), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [515] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(13), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [558] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(18), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [601] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(45), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [644] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(43), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [687] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(20), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [730] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(46), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [773] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(12), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [816] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(42), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [859] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(44), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [902] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(8), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [945] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(19), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [988] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_struct,
    STATE(40), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
  [1031] = 6,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      sym_float,
      sym_str,
      anon_sym_RBRACE,
    ACTIONS(134), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
  [1061] = 7,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_args_repeat1,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1085] = 6,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1106] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(142), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1125] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(144), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1144] = 6,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1165] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(146), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1184] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1202] = 5,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_GT,
    ACTIONS(150), 1,
      anon_sym_EQ,
    ACTIONS(92), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1220] = 4,
    ACTIONS(152), 1,
      sym_symbol,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      sym_field,
    STATE(66), 1,
      sym_fields,
  [1233] = 4,
    ACTIONS(156), 1,
      sym_symbol,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_param,
    STATE(64), 1,
      sym_params,
  [1246] = 3,
    ACTIONS(152), 1,
      sym_symbol,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_field,
  [1256] = 3,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_params_repeat1,
  [1266] = 3,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_fields_repeat1,
  [1276] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_args_repeat1,
  [1286] = 3,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_args_repeat1,
  [1296] = 3,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_fields_repeat1,
  [1306] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      aux_sym_fields_repeat1,
  [1316] = 3,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_params_repeat1,
  [1326] = 3,
    ACTIONS(152), 1,
      sym_symbol,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_field,
  [1336] = 3,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_params_repeat1,
  [1346] = 2,
    ACTIONS(156), 1,
      sym_symbol,
    STATE(61), 1,
      sym_param,
  [1353] = 1,
    ACTIONS(178), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1358] = 1,
    ACTIONS(186), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1363] = 2,
    ACTIONS(152), 1,
      sym_symbol,
    STATE(60), 1,
      sym_field,
  [1370] = 1,
    ACTIONS(191), 1,
      anon_sym_COLON,
  [1374] = 1,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
  [1378] = 1,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
  [1382] = 1,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
  [1386] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
  [1390] = 1,
    ACTIONS(201), 1,
      anon_sym_LBRACE,
  [1394] = 1,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
  [1398] = 1,
    ACTIONS(205), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 28,
  [SMALL_STATE(10)] = 54,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 106,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 226,
  [SMALL_STATE(17)] = 252,
  [SMALL_STATE(18)] = 278,
  [SMALL_STATE(19)] = 306,
  [SMALL_STATE(20)] = 338,
  [SMALL_STATE(21)] = 368,
  [SMALL_STATE(22)] = 394,
  [SMALL_STATE(23)] = 420,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 472,
  [SMALL_STATE(26)] = 515,
  [SMALL_STATE(27)] = 558,
  [SMALL_STATE(28)] = 601,
  [SMALL_STATE(29)] = 644,
  [SMALL_STATE(30)] = 687,
  [SMALL_STATE(31)] = 730,
  [SMALL_STATE(32)] = 773,
  [SMALL_STATE(33)] = 816,
  [SMALL_STATE(34)] = 859,
  [SMALL_STATE(35)] = 902,
  [SMALL_STATE(36)] = 945,
  [SMALL_STATE(37)] = 988,
  [SMALL_STATE(38)] = 1031,
  [SMALL_STATE(39)] = 1061,
  [SMALL_STATE(40)] = 1085,
  [SMALL_STATE(41)] = 1106,
  [SMALL_STATE(42)] = 1125,
  [SMALL_STATE(43)] = 1144,
  [SMALL_STATE(44)] = 1165,
  [SMALL_STATE(45)] = 1184,
  [SMALL_STATE(46)] = 1202,
  [SMALL_STATE(47)] = 1220,
  [SMALL_STATE(48)] = 1233,
  [SMALL_STATE(49)] = 1246,
  [SMALL_STATE(50)] = 1256,
  [SMALL_STATE(51)] = 1266,
  [SMALL_STATE(52)] = 1276,
  [SMALL_STATE(53)] = 1286,
  [SMALL_STATE(54)] = 1296,
  [SMALL_STATE(55)] = 1306,
  [SMALL_STATE(56)] = 1316,
  [SMALL_STATE(57)] = 1326,
  [SMALL_STATE(58)] = 1336,
  [SMALL_STATE(59)] = 1346,
  [SMALL_STATE(60)] = 1353,
  [SMALL_STATE(61)] = 1358,
  [SMALL_STATE(62)] = 1363,
  [SMALL_STATE(63)] = 1370,
  [SMALL_STATE(64)] = 1374,
  [SMALL_STATE(65)] = 1378,
  [SMALL_STATE(66)] = 1382,
  [SMALL_STATE(67)] = 1386,
  [SMALL_STATE(68)] = 1390,
  [SMALL_STATE(69)] = 1394,
  [SMALL_STATE(70)] = 1398,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, 0, 6),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, 0, 6),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 3, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 4),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6, 0, 8),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_smith(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
