#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_GT = 2,
  anon_sym_PLUS = 3,
  anon_sym_DASH = 4,
  anon_sym_STAR = 5,
  anon_sym_SLASH = 6,
  anon_sym_not = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  sym_int = 10,
  sym_float = 11,
  sym_str = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_COLON = 15,
  anon_sym_COMMA = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_fn = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_EQ = 21,
  sym_source_file = 22,
  sym_expr = 23,
  sym_binary_op = 24,
  sym_unary_op = 25,
  sym_paren = 26,
  sym_bool = 27,
  sym_param = 28,
  sym_params = 29,
  sym_block = 30,
  sym_fn = 31,
  sym_args = 32,
  sym_call = 33,
  sym_def = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_params_repeat1 = 36,
  aux_sym_args_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_str] = "str",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ] = "=",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [sym_paren] = "paren",
  [sym_bool] = "bool",
  [sym_param] = "param",
  [sym_params] = "params",
  [sym_block] = "block",
  [sym_fn] = "fn",
  [sym_args] = "args",
  [sym_call] = "call",
  [sym_def] = "def",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_str] = sym_str,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [sym_paren] = sym_paren,
  [sym_bool] = sym_bool,
  [sym_param] = sym_param,
  [sym_params] = sym_params,
  [sym_block] = sym_block,
  [sym_fn] = sym_fn,
  [sym_args] = sym_args,
  [sym_call] = sym_call,
  [sym_def] = sym_def,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_params = 6,
  field_return_type = 7,
  field_right = 8,
  field_type = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 3},
  [5] = {.index = 10, .length = 2},
  [6] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_args, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
    {field_value, 2},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
  [10] =
    {field_name, 0},
    {field_type, 2},
  [12] =
    {field_body, 4},
    {field_params, 1},
    {field_return_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '(', 13,
        ')', 14,
        '*', 11,
        '+', 8,
        ',', 20,
        '-', 10,
        '/', 12,
        ':', 19,
        '=', 24,
        '>', 7,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '(', 13,
        ')', 14,
        '*', 11,
        '+', 8,
        ',', 20,
        '-', 9,
        '/', 12,
        ':', 19,
        '=', 24,
        '>', 7,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(56),
    [sym_expr] = STATE(35),
    [sym_binary_op] = STATE(22),
    [sym_unary_op] = STATE(22),
    [sym_paren] = STATE(22),
    [sym_bool] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_call] = STATE(22),
    [sym_def] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
  },
  [2] = {
    [sym_args] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_symbol] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_not] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_int] = ACTIONS(23),
    [sym_float] = ACTIONS(21),
    [sym_str] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(29),
  },
  [3] = {
    [sym_expr] = STATE(35),
    [sym_binary_op] = STATE(22),
    [sym_unary_op] = STATE(22),
    [sym_paren] = STATE(22),
    [sym_bool] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_call] = STATE(22),
    [sym_def] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_symbol] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(36),
    [anon_sym_not] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(42),
    [sym_int] = ACTIONS(45),
    [sym_float] = ACTIONS(48),
    [sym_str] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_fn] = ACTIONS(54),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_symbol] = ACTIONS(59),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_not] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_int] = ACTIONS(59),
    [sym_float] = ACTIONS(57),
    [sym_str] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(59),
    [anon_sym_false] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_fn] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(57),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_symbol] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_not] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_int] = ACTIONS(63),
    [sym_float] = ACTIONS(61),
    [sym_str] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_fn] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(61),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_symbol] = ACTIONS(71),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(69),
    [anon_sym_not] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [sym_int] = ACTIONS(71),
    [sym_float] = ACTIONS(69),
    [sym_str] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_fn] = ACTIONS(71),
    [anon_sym_EQ] = ACTIONS(69),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_symbol] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(73),
    [anon_sym_not] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [sym_int] = ACTIONS(75),
    [sym_float] = ACTIONS(73),
    [sym_str] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_fn] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(73),
  },
  [8] = {
    [sym_expr] = STATE(35),
    [sym_binary_op] = STATE(22),
    [sym_unary_op] = STATE(22),
    [sym_paren] = STATE(22),
    [sym_bool] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_call] = STATE(22),
    [sym_def] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_fn] = ACTIONS(19),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_GT] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_not] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [sym_int] = ACTIONS(81),
    [sym_float] = ACTIONS(79),
    [sym_str] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_fn] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(79),
  },
  [10] = {
    [sym_expr] = STATE(35),
    [sym_binary_op] = STATE(22),
    [sym_unary_op] = STATE(22),
    [sym_paren] = STATE(22),
    [sym_bool] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_call] = STATE(22),
    [sym_def] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_symbol] = ACTIONS(87),
    [anon_sym_GT] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(85),
    [anon_sym_not] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [sym_int] = ACTIONS(87),
    [sym_float] = ACTIONS(85),
    [sym_str] = ACTIONS(85),
    [anon_sym_true] = ACTIONS(87),
    [anon_sym_false] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_fn] = ACTIONS(87),
    [anon_sym_EQ] = ACTIONS(85),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_symbol] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_not] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_int] = ACTIONS(63),
    [sym_float] = ACTIONS(61),
    [sym_str] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_fn] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(61),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_symbol] = ACTIONS(91),
    [anon_sym_GT] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(89),
    [anon_sym_not] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [sym_int] = ACTIONS(91),
    [sym_float] = ACTIONS(89),
    [sym_str] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(91),
    [anon_sym_false] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_fn] = ACTIONS(91),
    [anon_sym_EQ] = ACTIONS(89),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_symbol] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_not] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_int] = ACTIONS(63),
    [sym_float] = ACTIONS(61),
    [sym_str] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [anon_sym_fn] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(61),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_symbol] = ACTIONS(95),
    [anon_sym_GT] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(93),
    [anon_sym_not] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [sym_int] = ACTIONS(95),
    [sym_float] = ACTIONS(93),
    [sym_str] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(95),
    [anon_sym_false] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_fn] = ACTIONS(95),
    [anon_sym_EQ] = ACTIONS(93),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_symbol] = ACTIONS(99),
    [anon_sym_GT] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(97),
    [anon_sym_not] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [sym_int] = ACTIONS(99),
    [sym_float] = ACTIONS(97),
    [sym_str] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(99),
    [anon_sym_false] = ACTIONS(99),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_fn] = ACTIONS(99),
    [anon_sym_EQ] = ACTIONS(97),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_symbol] = ACTIONS(103),
    [anon_sym_GT] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_DASH] = ACTIONS(101),
    [anon_sym_STAR] = ACTIONS(101),
    [anon_sym_SLASH] = ACTIONS(101),
    [anon_sym_not] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_RPAREN] = ACTIONS(101),
    [sym_int] = ACTIONS(103),
    [sym_float] = ACTIONS(101),
    [sym_str] = ACTIONS(101),
    [anon_sym_true] = ACTIONS(103),
    [anon_sym_false] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_fn] = ACTIONS(103),
    [anon_sym_EQ] = ACTIONS(101),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_symbol] = ACTIONS(107),
    [anon_sym_GT] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(105),
    [anon_sym_not] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [sym_int] = ACTIONS(107),
    [sym_float] = ACTIONS(105),
    [sym_str] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(107),
    [anon_sym_false] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_fn] = ACTIONS(107),
    [anon_sym_EQ] = ACTIONS(105),
  },
  [19] = {
    [sym_expr] = STATE(35),
    [sym_binary_op] = STATE(22),
    [sym_unary_op] = STATE(22),
    [sym_paren] = STATE(22),
    [sym_bool] = STATE(22),
    [sym_fn] = STATE(22),
    [sym_call] = STATE(22),
    [sym_def] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_fn] = ACTIONS(19),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_symbol] = ACTIONS(113),
    [anon_sym_GT] = ACTIONS(111),
    [anon_sym_PLUS] = ACTIONS(111),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_not] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(111),
    [anon_sym_RPAREN] = ACTIONS(111),
    [sym_int] = ACTIONS(113),
    [sym_float] = ACTIONS(111),
    [sym_str] = ACTIONS(111),
    [anon_sym_true] = ACTIONS(113),
    [anon_sym_false] = ACTIONS(113),
    [anon_sym_COMMA] = ACTIONS(111),
    [anon_sym_LBRACE] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_fn] = ACTIONS(113),
    [anon_sym_EQ] = ACTIONS(111),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_symbol] = ACTIONS(117),
    [anon_sym_GT] = ACTIONS(115),
    [anon_sym_PLUS] = ACTIONS(115),
    [anon_sym_DASH] = ACTIONS(115),
    [anon_sym_STAR] = ACTIONS(115),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_not] = ACTIONS(117),
    [anon_sym_LPAREN] = ACTIONS(115),
    [anon_sym_RPAREN] = ACTIONS(115),
    [sym_int] = ACTIONS(117),
    [sym_float] = ACTIONS(115),
    [sym_str] = ACTIONS(115),
    [anon_sym_true] = ACTIONS(117),
    [anon_sym_false] = ACTIONS(117),
    [anon_sym_COMMA] = ACTIONS(115),
    [anon_sym_LBRACE] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_fn] = ACTIONS(117),
    [anon_sym_EQ] = ACTIONS(115),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_symbol] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_not] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_int] = ACTIONS(23),
    [sym_float] = ACTIONS(21),
    [sym_str] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [42] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(12), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [81] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(14), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [120] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(5), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [159] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(20), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [198] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(38), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [237] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(11), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [276] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(40), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [315] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(39), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [354] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(4), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [393] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(37), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [432] = 10,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_fn,
    STATE(41), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 7,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
  [471] = 5,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      sym_str,
      anon_sym_RBRACE,
    ACTIONS(123), 6,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
  [498] = 6,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_args_repeat1,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [519] = 4,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(131), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [535] = 5,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [553] = 4,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(135), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [569] = 4,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(137), 1,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [584] = 4,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [599] = 3,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_params_repeat1,
  [609] = 3,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_args_repeat1,
  [619] = 3,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_args_repeat1,
  [629] = 3,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_params_repeat1,
  [639] = 3,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_params_repeat1,
  [649] = 3,
    ACTIONS(157), 1,
      sym_symbol,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_param,
  [659] = 2,
    ACTIONS(157), 1,
      sym_symbol,
    STATE(50), 1,
      sym_param,
  [666] = 2,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_params,
  [673] = 1,
    ACTIONS(152), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [678] = 1,
    ACTIONS(163), 1,
      anon_sym_DASH_GT,
  [682] = 1,
    ACTIONS(165), 1,
      anon_sym_DASH_GT,
  [686] = 1,
    ACTIONS(167), 1,
      anon_sym_COLON,
  [690] = 1,
    ACTIONS(169), 1,
      anon_sym_DASH_GT,
  [694] = 1,
    ACTIONS(171), 1,
      anon_sym_DASH_GT,
  [698] = 1,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 42,
  [SMALL_STATE(25)] = 81,
  [SMALL_STATE(26)] = 120,
  [SMALL_STATE(27)] = 159,
  [SMALL_STATE(28)] = 198,
  [SMALL_STATE(29)] = 237,
  [SMALL_STATE(30)] = 276,
  [SMALL_STATE(31)] = 315,
  [SMALL_STATE(32)] = 354,
  [SMALL_STATE(33)] = 393,
  [SMALL_STATE(34)] = 432,
  [SMALL_STATE(35)] = 471,
  [SMALL_STATE(36)] = 498,
  [SMALL_STATE(37)] = 519,
  [SMALL_STATE(38)] = 535,
  [SMALL_STATE(39)] = 553,
  [SMALL_STATE(40)] = 569,
  [SMALL_STATE(41)] = 584,
  [SMALL_STATE(42)] = 599,
  [SMALL_STATE(43)] = 609,
  [SMALL_STATE(44)] = 619,
  [SMALL_STATE(45)] = 629,
  [SMALL_STATE(46)] = 639,
  [SMALL_STATE(47)] = 649,
  [SMALL_STATE(48)] = 659,
  [SMALL_STATE(49)] = 666,
  [SMALL_STATE(50)] = 673,
  [SMALL_STATE(51)] = 678,
  [SMALL_STATE(52)] = 682,
  [SMALL_STATE(53)] = 686,
  [SMALL_STATE(54)] = 690,
  [SMALL_STATE(55)] = 694,
  [SMALL_STATE(56)] = 698,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_args, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_args, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_args, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, 0, 6),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, 0, 6),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 3, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 5),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [173] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_smith(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
